from sent_mix import S, O, V, A, Av, V_ing, V_ed
#can choose real or nonsense proverbs by replacing the variable in chatbot_main.py
proverbs = ['The apple does not fall far from the tree.',
             'If you pay peanuts, you get monkeys.', 
             'All that glitters is not gold.',
             'Absence makes heart grow fonder.', 
             'A picture is worth a thousand words.', 
             'Action speaks louder than words.', 
             'A bird in the hand is worth two in the bush.', 
             'A fool and his money are soon parted.', 
             'An apple a day keeps the doctor away.', 
             'A happy heart is better than a full purse.', 
             'A jack of all trades is master of none.', 
             'When in Rome, do as the Romans do.', 
             'A journey of thousand miles begins with a single step.', 
             'Do not count your chickens before they hatch.', 
             'A leopard does not change its spots.', 
             'Every cloud has a silver lining.', 
             'All is fair in love and war.', 
             'A journey of a thousand miles begins with a single step.', 
             'A rising tide lifts all boats.', 
             'Necessity is the mother of invention.', 
             'If you cannot stand the heat, get out of the kitchen.', 
             'Two wrongs do not make a right.', 
             'Blood is thicker than water.', 
             'All is well that ends well.', 
             'The pen is mightier than the sword.', 
             'Among the blind, one-eyed man is king.', 
             'Rome was not built in a day.', 
             'A rolling stone gathers no moss.', 
             'Time waits for no one.', 
             'Ask no questions and hear no lies.', 
             'Too many cooks spoil the broth.', 
             'A stitch in time saves nine.', 
             'When there is smoke, there is fire.', 
             'As you sow, so you shall reap.', 
             'If it is not broke, do not fix it.', 
             'A tree is known by its fruit.', 
             'You cannot have your cake and eat it too.', 
             'Barking dogs seldom bite.', 
             'Beauty is in the eye of beholder.', 
             'Be slow in choosing, but slower in changing.', 
             'Best things in life are free.', 
             'Better late than never.', 
             'Curiosity killed the cat.', 
             'Different strokes for different folks.', 
             'Do not bite the hand that feeds you.', 
             'Do not carry coals to Newcastle.', 
             'Do not cast pearls before swine.', 
             'Do not cross the bridge till you come to it.', 
             'Do not judge a book by its cover.', 
             'Do not put all your eggs in one basket.', 
             'Do not throw the baby with the bathwater.', 
             'Early bird catches the worm.', 
             'Every dog has his day.', 
             'Fine feathers make fine birds.', 
             'Fools rush in where angels fear to tread.', 
             'Fortune favors the brave.', 
             'God helps those who help themselves.', 
             'Good things come to those who wait.', 
             'Half a loaf is better than none.', 
             'Home is where the heart is.', 
             'Honesty is the best policy.', 
             'Hope for the best, but prepare for the worst.', 
             'If wishes were horses, beggars would ride.', 
             'If you cannot beat them, join them.', 
             'If you play with fire, you will get burned.', 
             'If you want peace, prepare for war.', 
             'Ignorance is bliss.', 
             'It is better to be safe than sorry.', 
             'It is better to lose the battle and win the war.', 
             'It is never too late to mend.', 
             'It takes a village to raise a child.', 
             'It takes two to tango.', 
             'Kind words will unlock an iron door.', 
             'Laughter is the best medicine.', 
             'Learn to walk before you run.', 
             'Let sleeping dogs lie.', 
             'Look before you leap.', 
             'Love me, love my dog.', 
             'Money does not grow on trees.', 
             'Murder will out.', 
             'Never put off until tomorrow what you can do today.', 
             'Never test the depth of water with both feet.', 
             'No gain without pain.', 
             'No news is good news.', 
             'Once bitten twice shy.', 
             'One man\’s junk is another man\’s treasure.', 
             'Pen is mightier than sword.', 
             'People who live in glass houses should not throw stones.', 
             'Politeness costs little but yields much.', 
             'Practice makes perfect.', 
             'Slow and steady wins the race.', 
             'Strike while the iron is hot.', 
             'The course of true love never did run smooth.', 
             'The grass is greener on the other side of fence.', 
             'The harder you work, the luckier you get.', 
             'The only free cheese is in the mousetrap.', 
             'The proof of pudding is in eating.', 
             'There are many paths to the top of the mountain, but the view is always the same.', 
             'There is no time like the present.', 
             'The road to hell is paved with good intentions.', 
             'The squeaky wheel gets the grease.', 
             'Two heads are better than one.', 
             'Where there is will, there is way.', 
             'While the cat is away, the mice will play.', 
             'Words must be weighed, not counted.', 
             'You can catch more flies with honey than with vinegar.', 
             'You can lead a horse to water, but you cannot make it drink.', 
             'You cannot make an omelet without breaking eggs.', 
             'You can teach an old dog new tricks.', 
             'You show me the man, and I will show you the rule.']

proverb_twist = [f'The {S} does not fall far from the {O}.',
                 f'If you pay {S}, you get {O}.', 
                 f'All that {V} is not {O}.', 
                 f'{S.capitalize()} makes {O} grow {A}.', 
                 f'A {S} is worth a thousand {O}s.', 
                 f'{S.capitalize()}s speak louder than {O}s.', 
                 f'A {S} in the hand is worth two in the {O}.', 
                 f'A {S} and his {O} are soon {V_ed}.', 
                 f'An {S} a day keeps the {O} away.', 
                 f'A {A} {S} is better than a {A} {O}.', 
                 f'When in {S}, do as the {O}s do.', 
                 f'A journey of a thousand {S}s begins with a single {O}.', 
                 f'Do not count your {S}s before they {V}.', 
                 f'A {S} does not change its {O}s.', 
                 f'Every {S} has a {A} {O}.', 
                 f'All is {A} in love and {O}.', 
                 f'A rising {S} lifts all {O}s.', 
                 f'{S.capitalize()} is the {S} of {O}.', 
                 f'If you cannot stand the {S}, get out of the {O}.', 
                 f'Two {S}s do not make a {O}.', 
                 f'{S.capitalize()} is thicker than {O}.', 
                 f'All is well that {V}s well.', 
                 f'The {S} is mightier than the {O}.', 
                 f'Among the {S}s, one-eyed {O} is king.', 
                 f'{S.capitalize()} was not {V_ed} in a day.', 
                 f'A {V_ing} {S} gathers no {O}.', 
                 f'{S.capitalize()} waits for no {O}.', 
                 f'Ask no {S}s and hear no {O}s.', 
                 f'Too many {S}s spoil the {O}.', 
                 f'A {S} in time saves nine.', 
                 f'Where there is {S}, there is {O}.', 
                 f'As you {V}, so you shall {V}.', 
                 f'If it is not {V_ed}, do not {V} it.', 
                 f'A {S} is known by its {O}.', 
                 f'You cannot have your {O} and {V} it too.', 
                 f'{V_ing.capitalize()} {S}s seldom bite.', 
                 f'{S.capitalize()} is in the eye of the beholder.', 
                 f'Be slow in {V_ing}, but slower in {V_ing}.', 
                 f'{A.capitalize()} {S}s in life are free.', 
                 f'Better {Av} than {Av}.', 
                 f'Curiosity {V_ed} the {O}.', 
                 f'Different {S}s for different {O}s.', 
                 f'Do not {V} the {S} that {V}s you.', 
                 f'Do not carry {S}s to Newcastle.', 
                 f'Do not cast {S}s before {O}.', 
                 f'Do not {V} the {O} till you come to it.', 
                 f'Do not {V} a {S} by its {O}.', 
                 f'Do not put all your {S}s in one {O}.', 
                 f'Do not throw out the {S} with the {O}.', 
                 f'{A.capitalize()} {S} catches the {O}.', 
                 f'Every {S} has his day.', 
                 f'Fine {S}s make fine {O}s.', 
                 f'{S.capitalize()}s rush in where {O}s fear to tread.', 
                 f'{S.capitalize()} favors the {A}.', 
                 f'{S.capitalize()} helps those who help themselves.', 
                 f'Good {S}s come to those who wait.', 
                 f'Half a {S} is better than none.', 
                 f'Home is where the {S} is.', 
                 f'{S.capitalize()} is the best policy.', 
                 f'Hope for the {S}, but prepare for the {O}.', 
                 f'If {S}s were horses, {O}s would ride.', 
                 f'If you cannot {V} them, {V} them.', 
                 f'If you play with {S}, you will get {V_ed}.', 
                 f'If you want {S}, prepare for {O}.', 
                 f'{S.capitalize()} is bliss.', 
                 f'It is better to be {A} than {A}.', 
                 f'It is {A} to lose the {S} and win the {O}.', 
                 f'It is never too {A} to {V}.', 
                 f'It takes a {S} to raise a {O}.', 
                 f'It takes {S} to tango.', 
                 f'{A.capitalize()} {S}s will unlock an iron door.', 
                 f'{S.capitalize()} is the best medicine.', 
                 f'Learn to {V} before you {V}.', 
                 f'Let {V_ing} {S}s lie.', 
                 f'{V.capitalize()} before you {V}.', 
                 f'Love me, love my {O}.', 
                 f'{S.capitalize()} does not {V} on trees.', 
                 f'{S.capitalize()} will out.', 
                 f'Never put off until tomorrow what you can {V} today.', 
                 f'Never test the depth of {S} with both {O}s.', 
                 f'No {S} without {O}.', 
                 f'No {S} is good {S}.', 
                 f'Once {V_ed} twice {A}.', 
                 f'One person\’s {S} is another one\’s {O}.', 
                 f'{S.capitalize()}s who live in glass houses should not throw {O}s.', 
                 f'{S.capitalize()} costs little but yields much.', 
                 f'{S.capitalize()} makes {A}.', 
                 f'{A.capitalize()} and {A} wins the {O}.', 
                 f'Strike while the {O} is {A}.', 
                 f'The course of true {O} never did run smooth.', 
                 f'The {S} is {A}er on the other side of {O}.', 
                 f'The harder you {V}, the {A}er you get.', 
                 f'The only free {S} is in the mousetrap.', 
                 f'The proof of {O} is in {V_ing}.', 
                 f'There are many paths to the top of the {S}, but the view is always the same.', 
                 f'There is no time like the {S}.', 
                 f'The road to {S} is paved with good {O}s.', 
                 f'The squeaky {S} gets the grease.', 
                 f'Two {S}s are better than one.', 
                 f'Where there is {S}, there is {O}.', 
                 f'While the {S} is away, the {O} will play.', 
                 f'{S.capitalize()}s must be weighed, not counted.', 
                 f'You can catch more {S}s with {O} than with {O}.', 
                 f'You can lead a {S} to water, but you cannot make it {V}.', 
                 f'You cannot {V} an omelet without {V_ing} eggs.', 
                 f'You can {V} an old {O} new tricks.', 
                 f'You show me the {S}, and I will show you the {O}.']
